### PR TITLE
Popped up laws done right

### PR DESCRIPTION
**Pull request by mdrie**
Yesterdays PR still had errors: Selecting a law pushed the stack down to the table, again. Not my intention at all!

This was a little more complex, since there are some conflicting mouse events and more care has to be taken. Also did some fixes to animations and stuff.

No real review needed. Might be interesting for you. I can explain things, if you have questions - but not till Sunday evening...

Please do a merge commit and not a rebase. I came to understand the advantages.

### CODE REVIEW

**Comment by jschirrmacher** [comment]
That looks great! And I like putting back the laws.
Regrettably, Cypress doesn't run on my machine any more, so I don't know why the tests fail.

**Review by jschirrmacher — APPROVED** [review]

**Comment by mdrie** [comment]
> That looks great! And I like putting back the laws. Regrettably, Cypress doesn't run on my machine any more, so I don't know why the tests fail.

It came to me, why the test prbly fails: The test clicks on Aussitzen multiple times, but The button only appears after the animation ends now. I guess a  `cy.wait(600)` would do it.

**Comment by jschirrmacher** [comment]
I found another problem with the law proposals (at least in the #186 branch), which might be related. The click on the stack of proposed laws first tries to take them up, but the click event is then propagated to the layer above and so the laws are taken back to the desk - and the user sees no action!
A `@click.prevent` prevents this propagation and it works like expected.

**Comment by jschirrmacher** [comment]
However, that does not seem to be enough. With this change, it is not possible to accept a law any more. I suppose, I need the changes from this PR as well...

**Comment by mdrie** [comment]
> I found another problem with the law proposals (at least in the #186 branch), which might be related. The click on the stack of proposed laws first tries to take them up, but the click event is then propagated to the layer above and so the laws are taken back to the desk - and the user sees no action! A `@click.prevent` prevents this propagation and it works like expected.

That is exactly what i fixed in this PR - it was a bit more complicated, though.

**Pull request merged**
