### PR TITLE
Show progress bars for the three indicators

### PR DESCRIPTION
**Pull request by jschirrmacher**

### CODE REVIEW

**Comment by jschirrmacher** [comment]
Closes #121

Is this what you thought of @mdrie?

**Review by mdrie — APPROVED** [review]
Very nice!

Actual numbers might be a good idea later. But lets play with this version a little and see what the others say.

We should try and remember the issue. The description shows a possible way to display the numbers - if wanted/needed.

**Comment by mdrie** [comment]
Strange! The Issue was not closed by merging this PR... What is wrong?

**Comment by mdrie** [comment]
Will now try to link the issue by hand.

**Comment by mdrie** [comment]
closes #121

**Comment by mdrie** [comment]
Guess, that does not work after merging?

**Pull request merged**
