### PR TITLE
Game machine

### PR DESCRIPTION
**Pull request by mdrie**
@jschirrmacher Something is broken and I have no clue, what.
- Unit tests work,
- `npm build` works.
- `npm serve` works and shows app.
- BUT `npm dev` does not. Browsers complain with "Uncaught ReferenceError: can't access lexical declaration 'AbstandsregelnFuerWindkraftAbschaffen' before initialization"

### CODE REVIEW

**Comment by jschirrmacher** [comment]
> Browsers complain with "Uncaught ReferenceError: can't access lexical declaration 'AbstandsregelnFuerWindkraftAbschaffen' before initialization"

Where exactly does this error message occur? Do you have a stack trace?

**Comment by mdrie** [comment]
```
Uncaught ReferenceError: can't access lexical declaration 'AbstandsregelnFuerWindkraftAbschaffen' before initialization
    <anonymous> index.ts:63
index.ts:63:2
    <anonym> index.ts:63
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    evaluation self-hosted:2332
```

**Comment by mdrie** [comment]
Brave shows: 
```
Uncaught ReferenceError: Cannot access 'AbstandsregelnFuerWindkraftAbschaffen' before initialization
    at index.ts:63
```
its `src/laws/index.ts`

**Comment by jschirrmacher** [comment]
It seems like the problem is located in AbstandsregelnFuerWindkraftAbschaffen itself. It is imported just like all other laws, but in contrast to these, it is `undefined` when used in `lawList`. Strange that it doesn't differ much from other laws like e.g. `AbstandsregelnFuerWindkraftLockern`.

**Comment by jschirrmacher** [comment]
Bildschirmfoto 2021-08-18 um 18 18 04

**Comment by jschirrmacher** [comment]
While removing some other laws doesn't change anything (I hoped the problem would "move" to another law then, so the cause could be the sheer amount of laws), removing just this one law solves the problem.

I'm convinced now, that the law itself has some (yet still unknown) problem.

**Comment by mdrie** [comment]
It has to do with it also being referenced in the event `AbstandsregelnWindkraft.ts`: When I remove it there, the problem moves to `AbstandsregelnWindkraftLockern.ts`.  Maybe we should use IDs there, anyway?

**Comment by mdrie** [comment]
If I remove all references to laws from `AbstandsregelnWindkraft.ts` and `Altbausanierung.ts` the problem goes away...

**Comment by jschirrmacher** [comment]
Ah, so a cyclic reference might be the reason!

Yes, using IDs might be a good idea here! 👏

**Comment by mdrie** [comment]
cyclic references should be detectable somehow, shouldn't they?

I found `madge` to find cycles in imports - found none. But i got the feeling, there are cycles possible without explicit imports.

**Comment by mdrie** [comment]
I change to IDs right now.

**Comment by mdrie** [comment]
Thanks!!!

**Review by jschirrmacher — APPROVED** [review]
LGTM

**Comment by jschirrmacher** [comment]
Is this still WIP? Looks like it works now?

**Comment by mdrie** [comment]
Thanks, but the actual change is still to come: Merging LawProposer and EventMachine...

**Comment by mdrie** [comment]
Unit tests could be more complete. Only fixed the old ones from LawProposer. The ones from EventMachine do not apply easily - removed in a separate commit. Will open issue for that.

**Comment by mdrie** [comment]
@jschirrmacher This was ready for merge before my leave. Did you look at it? Anything to complain about?

**Comment by jschirrmacher** [comment]
Actually, I didn't, because I didn't know that it is ready.
Now, I had a look and find it very helpful.
The only thing I see is that we lose some validation when using laws in events, because there are only the names instead of the laws itself. But I don't have any solution for this, so imo we could merge it. Maybe we find some other way later.

**Review by jschirrmacher — APPROVED** [review]

**Comment by mdrie** [comment]
Thanks!

> The only thing I see is that we lose some validation when using laws in events, because there are only the names instead of the laws itself. But I don't have any solution for this, so imo we could merge it. Maybe we find some other way later.

Which validation do we loose? Now `type LawId = "AllesBleibtBeimAlten" | "InitialAtomausstieg" | ...` and not just `string` anymore.

**Pull request merged**
